### ISSUE TITLE
可以自己删掉一些分组吗？

### ISSUE THREAD

**Issue by ghost** [zsokami/ACL4SSR#2]
你好，我想删掉下面的国家分组，请问这需要怎么操作呢？
![屏幕截图 2023-04-16 185840](https://user-images.githubusercontent.com/58248905/232303141-a48c2390-eb9a-4d50-b14f-6bc2f09395b7.png)

**Comment by zsokami** [comment]
新增了去除国家/地区的版本

**Comment by zsokami** [comment]
新增了订阅转换反代可自动去除无节点的分组 `https://dd.al/scm?url={原订阅链接}`

**Comment by ghost** [comment]
> 新增了去除国家/地区的版本

你好，我需要把链接转为quanx的订阅，但是这个去除国家地区的版本只提供了短链，请问短链怎么设置为target=quanx呢？》

**Comment by zsokami** [comment]
> 你好，我需要把链接转为quanx的订阅，但是这个去除国家地区的版本只提供了短链，请问短链怎么设置为target=quanx呢？》

短链不支持设置参数。直接用订阅转换后端的话设置 config=https://dd.al/config-nc 即可，如 `https://api.dler.io/sub?target=quanx&config=https://dd.al/config-nc&url={原订阅链接}`

**Comment by ghost** [comment]
> https://api.dler.io/sub?target=quanx&config=https://dd.al/config-nc&url=

谢谢，我使用这个转链接后，还是有专线和国家分组，可以帮我看一下吗？
![IMG_2624](https://user-images.githubusercontent.com/58248905/235184403-aa293207-8b0e-4569-b409-ceb05be0309c.png)

**Comment by zsokami** [comment]
@douxy1994 这些分组显然不是我的，你可能链接写错了，先试试这个正不正确：https://api.dler.io/sub?target=quanx&config=https://dd.al/config-nc&url=https://sub.pmsub.me/clash.yaml

**Comment by ghost** [comment]
> @douxy1994 这些分组显然不是我的，你可能链接写错了，先试试这个正不正确：https://api.dler.io/sub?target=quanx&config=https://dd.al/config-nc&url=https://sub.pmsub.me/clash.yaml

重新更新后正常了，不显示国家了。有可能是我使用配置的问题，但现在自定义策略已经显示成你的分组了。非常感谢，五一快乐～
