### ISSUE TITLE
希望github可以单独设置代理

### ISSUE THREAD

**Issue by Summer-Tail** [zsokami/ACL4SSR#5]
希望github可以单独设置代理

**Comment by zsokami** [comment]
ACL4SSR 有提供 [Github 规则](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Github.list) 可直接使用

在 `ruleset=🤖 ‍AI` 之下加一行：
```
ruleset=GitHub,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
```
然后在 `custom_proxy_group=🤖 ‍AI` 之下加一行 `custom_proxy_group=GitHub...` 自定义你的策略组

如果只需要单独设置某个国家/地区，可以这样写：
```
custom_proxy_group=GitHub`select`[]✈️ ‍起飞`[]🛩️ ‍墙内`[]🇭🇰 ‍香港`[]🇹🇼 ‍台湾`[]🇨🇳 ‍中国`[]🇸🇬 ‍新加坡`[]🇯🇵 ‍日本`[]🇺🇸 ‍美国`[]🎏 ‍其他`[]👆🏻 ‍指定`[]👆🏻🇭🇰 ‍香港`[]👆🏻🇹🇼 ‍台湾`[]👆🏻🇨🇳 ‍中国`[]👆🏻🇸🇬 ‍新加坡`[]👆🏻🇯🇵 ‍日本`[]👆🏻🇺🇸 ‍美国`[]👆🏻🎏 ‍其他
```
如果需要单独设置某个节点，可以添加所有节点进去：
```
custom_proxy_group=GitHub`select`^
```
